spring:
  ai:
    openai:
      # Replace with your actual OpenAI API Key
      api-key: YOUR_OPENAI_API_KEY_HERE
    mcp:
      client:
        stdio:
          root-change-notification: true
          connections:
            server1:
              command: /path/to/server
              args:
                - --port=8080
                - --mode=production
              env:
                API_KEY: your-api-key
                DEBUG: "true"
        sse:
          connections:
            server1:
              url: http://otherserver:8081
              sse-endpoint: /custom-sse
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
